FROM node:alpine

RUN apk add openjdk11

RUN npm install -g firebase-tools

WORKDIR /app
RUN   echo "{"emulators":{"firestore":{"port":8080,"host":"0.0.0.0"}}}" > firebase.json


CMD [ "firebase", "--project=better-caspr", "emulators:start", "--only", "firestore" ]

