# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Self-Hosted Deploy

on:
  push:
    branches: [ main ] # for now
  workflow_dispatch:


jobs:
  deploy:
    runs-on: [self-hosted, Linux]
    permissions:
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Kill all other containers
        continue-on-error: true
        run: |
          docker kill $(docker ps -q)
      - name: Run
        run: |-
          docker-compose build --pull --no-cache
          docker compose up --detach --remove-orphans --wait
